// Utilities
import { h } from 'vue';
import type { IconSet, IconAliases, IconProps } from 'vuetify'
import {VComponentIcon} from "vuetify/components/VIcon";
import {
    IconChevronUp,
    IconChevronLeft,
    IconChevronRight,
    IconChevronDown,
    IconCheck,
    IconCircleXFilled,
    IconX,
    IconCircleCheckFilled,
    IconInfoCircleFilled,
    IconAlertCircleFilled,
    IconSquareCheckFilled,
    IconSquare,
    IconCircleFilled,
    IconArrowUp,
    IconArrowDown,
    IconMenu2,
    IconCaretDown,
    IconInnerShadowLeftFilled,
    IconInnerShadowLeft,
    IconPencil,
    IconStarFilled,
    IconStarHalfFilled,
    IconStar,
    IconRefresh,
    IconChevronsLeft,
    IconChevronsRight,
    IconPaperclip,
    IconSelector,
    IconPlus,
    IconMinus,
    IconSquareMinus,
    IconSearch,
    IconLanguage,
    IconBrightnessDown,
    IconMoonStars,
    IconPointFilled,
    IconLayoutDashboard,
    IconPoint,
    IconEye,
    IconEyeOff,
    IconMail,
    IconPassword,
    IconLogout,
    IconSettings, Icon123, IconPhone, IconDots, IconTextCaption, IconUser
} from "@tabler/icons-vue"

const aliases: IconAliases = {
    collapse: IconChevronUp,
    complete: IconCheck,
    cancel: IconCircleXFilled,
    close: IconX,
    delete: IconCircleXFilled,
    // delete (e.g. v-chip close)
    clear: IconCircleXFilled,
    success: IconCircleCheckFilled,
    info: IconInfoCircleFilled,
    warning: IconAlertCircleFilled,
    error: IconCircleXFilled,
    prev: IconChevronLeft,
    next: IconChevronRight,
    checkboxOn: IconSquareCheckFilled,
    checkboxOff: IconSquare,
    checkboxIndeterminate: IconSquareMinus,
    delimiter: IconCircleFilled,
    // for carousel
    sortAsc: IconArrowUp,
    sortDesc: IconArrowDown,
    expand: IconChevronDown,
    menu: IconMenu2,
    subgroup: IconCaretDown,
    dropdown: IconCaretDown,
    radioOn: IconInnerShadowLeftFilled,
    radioOff: IconInnerShadowLeft,
    edit: IconPencil,
    ratingEmpty: IconStar,
    ratingFull: IconStarFilled,
    ratingHalf: IconStarHalfFilled,
    loading: IconRefresh,
    first: IconChevronsLeft,
    last: IconChevronsRight,
    unfold: IconSelector,
    file: IconPaperclip,
    plus: IconPlus,
    minus: IconMinus,
    //Custom
    dashboard: IconLayoutDashboard,
    search: IconSearch,
    language: IconLanguage,
    light: IconBrightnessDown,
    dark: IconMoonStars,
    dot: IconPointFilled,
    point: IconPoint,
    eye: IconEye,
    'eye-off': IconEyeOff,
    email: IconMail,
    password: IconPassword,
    settings: IconSettings,
    numeric: Icon123,
    phone: IconPhone,
    dots: IconDots,
    text: IconTextCaption,
    user: IconUser,
    logout: IconLogout,
}

const tabler: IconSet = {
    component: (props: IconProps) => h(VComponentIcon, props),
}

export { aliases, tabler }